CREATE TABLE EMPLOYEE (
    Employee_ID VARCHAR(10) PRIMARY KEY,
    Employee_Name VARCHAR(50),
    Dept_ID VARCHAR(10),

    FOREIGN KEY (Dept_ID)
        REFERENCES DEPARTMENT(Dept_ID)
);
CREATE TABLE MANAGER (
    Manager_ID VARCHAR(10) PRIMARY KEY,
    Manager_Name VARCHAR(50)
);
CREATE TABLE DEPARTMENT (
    Dept_ID VARCHAR(10) PRIMARY KEY,
    Dept_Name VARCHAR(50),
    Dept_Location VARCHAR(50),
    Manager_ID VARCHAR(10),

    FOREIGN KEY (Manager_ID)
        REFERENCES MANAGER(Manager_ID)
);
